name: build-and-deploy

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: salvatierraj/gestura-back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=tag

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: salvatierraj
          password: "7@21sd08VJ"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:ci
          args: "--hostname gha-deployer --timeout 2m"

      - name: Quick debug
        run: |
          echo "Runner IPs:"
          ip a || true
          echo "Trying Tailscale ping:"
          ping -c 2 100.66.227.22 || true

      - name: Deploy over SSH via Tailscale
        uses: appleboy/ssh-action@v1
        with:
          host: 100.66.227.22
          username: ${{ secrets.SSH_USER }}    
          key: ${{ secrets.SSH_KEY }}         
          script: |
            set -e
            APP_DIR=/opt/gestura-back
            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            # Login a Docker Hub con secret
            echo "7@21sd08VJ" | docker login docker.io -u "salvatierraj" --password-stdin

            # Traer última imagen y levantar
            docker compose pull
            docker compose up -d --remove-orphans

            # Limpieza
            docker image prune -f
